// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type HealthResponse struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Version string `json:"version"`
}
