// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type AccountDisplayProfileResponse struct {
	Nickname          *string `json:"nickname,optional"`
	ManagementVersion int64   `json:"management_version"`
}

type AccountMutationRequest struct {
	AccountID         string `path:"accountId"`
	ManagementVersion int64  `json:"management_version"`
	OperationID       string `json:"operation_id"`
}

type AddRoomExaminationItemAPIRequest struct {
	RoomID      string `path:"roomId"`
	ItemID      string `json:"item_id"`
	OperationID string `json:"operation_id"`
}

type AdminAccountDetailResponse struct {
	AccountID               string   `json:"account_id"`
	Nickname                *string  `json:"nickname,optional"`
	DisplayName             *string  `json:"display_name,optional"`
	AvatarURL               *string  `json:"avatar_url,optional"`
	MaskedPhone             *string  `json:"masked_phone,optional"`
	AccountStatus           string   `json:"account_status"`
	IdentityType            string   `json:"identity_type"`
	DepartmentID            *string  `json:"department_id,optional"`
	DepartmentName          *string  `json:"department_name,optional"`
	ManagementVersion       int64    `json:"management_version"`
	PhoneVerificationStatus *string  `json:"phone_verification_status,optional"`
	StaffNo                 *string  `json:"staff_no,optional"`
	Description             *string  `json:"description,optional"`
	Roles                   []string `json:"roles"`
	AuthorizationVersion    int64    `json:"authorization_version"`
	AvailableActions        []string `json:"available_actions"`
	CreatedAt               string   `json:"created_at"`
	UpdatedAt               string   `json:"updated_at"`
	StaffStatus             *string  `json:"staff_status,optional"`
}

type AdminAccountPathRequest struct {
	AccountID string `path:"accountId"`
}

type AdminAccountSummaryResponse struct {
	AccountID         string  `json:"account_id"`
	Nickname          *string `json:"nickname,optional"`
	DisplayName       *string `json:"display_name,optional"`
	AvatarURL         *string `json:"avatar_url,optional"`
	MaskedPhone       *string `json:"masked_phone,optional"`
	AccountStatus     string  `json:"account_status"`
	IdentityType      string  `json:"identity_type"`
	DepartmentID      *string `json:"department_id,optional"`
	DepartmentName    *string `json:"department_name,optional"`
	ManagementVersion int64   `json:"management_version"`
}

type AdminOrganizationUnitResponse struct {
	UnitID      string `json:"unit_id"`
	ParentID    string `json:"parent_id,optional"`
	UnitType    string `json:"unit_type"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Status      string `json:"status"`
	ChildCount  int64  `json:"child_count"`
	DoctorCount int64  `json:"doctor_count"`
	Version     int64  `json:"version"`
}

type AdminSearchAccountByPhoneRequest struct {
	Phone string `json:"phone"`
}

type AdminSearchAccountByPhoneResponse struct {
	Identity AdminAccountSummaryResponse `json:"identity"`
	Phone    PhoneBindingResponse        `json:"phone"`
}

type AppointmentRoomPathRequest struct {
	RoomID string `path:"roomId"`
}

type AppointmentRoomResponse struct {
	RoomID       string `json:"room_id"`
	DepartmentID string `json:"department_id"`
	CampusID     string `json:"campus_id"`
	Building     string `json:"building"`
	FloorNumber  int32  `json:"floor_number"`
	RoomNumber   string `json:"room_number"`
	DisplayName  string `json:"display_name"`
	Version      int64  `json:"version"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type CampusSummaryResponse struct {
	CampusID        string `json:"campus_id"`
	HospitalID      string `json:"hospital_id"`
	Code            string `json:"code"`
	Name            string `json:"name"`
	DepartmentCount int64  `json:"department_count"`
	Status          string `json:"status"`
	Version         int64  `json:"version"`
}

type ChangeAppointmentResourceStatusRequest struct {
	ResourceID      string `path:"resourceId"`
	ExpectedVersion int64  `json:"expected_version"`
	OperationID     string `json:"operation_id"`
}

type ChangeDoctorDepartmentRequest struct {
	AccountID         string `path:"accountId"`
	DepartmentID      string `json:"department_id"`
	ManagementVersion int64  `json:"management_version"`
	OperationID       string `json:"operation_id"`
}

type ChangeExaminationItemStatusRequest struct {
	ItemID          string `path:"itemId"`
	ExpectedVersion int64  `json:"expected_version"`
	OperationID     string `json:"operation_id"`
}

type ChangeOrganizationUnitStatusRequest struct {
	UnitID      string `path:"unitId"`
	Version     int64  `json:"version"`
	OperationID string `json:"operation_id"`
}

type CreateAppointmentRoomRequest struct {
	DepartmentID string `json:"department_id"`
	CampusID     string `json:"campus_id"`
	Building     string `json:"building"`
	FloorNumber  int32  `json:"floor_number"`
	RoomNumber   string `json:"room_number"`
	OperationID  string `json:"operation_id"`
}

type CreateExaminationItemRequest struct {
	OwnerDepartmentID string `json:"owner_department_id"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	OperationID       string `json:"operation_id"`
}

type CreateOrganizationUnitRequest struct {
	UnitType    string `json:"unit_type"`
	ParentID    string `json:"parent_id"`
	Name        string `json:"name"`
	OperationID string `json:"operation_id"`
}

type CurrentIdentityResponse struct {
	AccountID            string   `json:"account_id"`
	AccountType          string   `json:"account_type"`
	Status               string   `json:"status"`
	Roles                []string `json:"roles"`
	DepartmentID         string   `json:"department_id,optional"`
	Permissions          []string `json:"permissions"`
	AuthorizationVersion int64    `json:"authorization_version"`
}

type DepartmentSummaryResponse struct {
	DepartmentID string `json:"department_id"`
	CampusID     string `json:"campus_id"`
	CampusName   string `json:"campus_name"`
	Code         string `json:"code"`
	Name         string `json:"name"`
	DoctorCount  int64  `json:"doctor_count"`
	Status       string `json:"status"`
	Version      int64  `json:"version"`
}

type DirectoryDoctorPathRequest struct {
	DepartmentID string `path:"departmentId"`
	Page         int64  `form:"page,default=1"`
	PageSize     int64  `form:"page_size,default=20"`
}

type DoctorSummaryResponse struct {
	AccountID    string  `json:"account_id"`
	DisplayName  string  `json:"display_name"`
	DepartmentID string  `json:"department_id"`
	AvatarURL    *string `json:"avatar_url,optional"`
	Description  *string `json:"description,optional"`
	Version      int64   `json:"version"`
}

type ExaminationItemPathRequest struct {
	ItemID string `path:"itemId"`
}

type ExaminationItemResponse struct {
	ItemID            string `json:"item_id"`
	OwnerDepartmentID string `json:"owner_department_id"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	Status            string `json:"status"`
	Version           int64  `json:"version"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type HealthResponse struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Version string `json:"version"`
}

type HospitalSummaryResponse struct {
	HospitalID string `json:"hospital_id"`
	Code       string `json:"code"`
	Name       string `json:"name"`
	Version    int64  `json:"version"`
}

type ItemRoomsPathRequest struct {
	ItemID string `path:"itemId"`
}

type ItemWeeklyWindowResponse struct {
	WindowID          string `json:"window_id"`
	ItemID            string `json:"item_id"`
	Weekday           int32  `json:"weekday"`
	Session           string `json:"session"`
	StartTime         string `json:"start_time"`
	BookingCutoffTime string `json:"booking_cutoff_time"`
	EndTime           string `json:"end_time"`
	Status            string `json:"status"`
	Version           int64  `json:"version"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type ListAdminAccountsRequest struct {
	Page         int64  `form:"page,default=1"`
	PageSize     int64  `form:"page_size,default=20"`
	Nickname     string `form:"nickname,optional"`
	IdentityType string `form:"identity_type,optional"`
	Status       string `form:"status,optional"`
	DepartmentID string `form:"department_id,optional"`
}

type ListAdminAccountsResponse struct {
	Items    []AdminAccountSummaryResponse `json:"items"`
	Page     int64                         `json:"page"`
	PageSize int64                         `json:"page_size"`
	Total    int64                         `json:"total"`
}

type ListAppointmentRoomsRequest struct {
	DepartmentID string `form:"department_id"`
	Page         int64  `form:"page,default=1"`
	PageSize     int64  `form:"page_size,default=20"`
}

type ListAppointmentRoomsResponse struct {
	Rooms    []AppointmentRoomResponse `json:"rooms"`
	Page     int64                     `json:"page"`
	PageSize int64                     `json:"page_size"`
	Total    int64                     `json:"total"`
}

type ListDepartmentsRequest struct {
	CampusID string `form:"campus_id"`
}

type ListDepartmentsResponse struct {
	Items []DepartmentSummaryResponse `json:"items"`
}

type ListDoctorsResponse struct {
	Items    []DoctorSummaryResponse `json:"items"`
	Page     int64                   `json:"page"`
	PageSize int64                   `json:"page_size"`
	Total    int64                   `json:"total"`
}

type ListExaminationItemsRequest struct {
	OwnerDepartmentID string `form:"owner_department_id,optional"`
	Status            string `form:"status,optional"`
	Page              int64  `form:"page,default=1"`
	PageSize          int64  `form:"page_size,default=20"`
}

type ListExaminationItemsResponse struct {
	Items    []ExaminationItemResponse `json:"items"`
	Page     int64                     `json:"page"`
	PageSize int64                     `json:"page_size"`
	Total    int64                     `json:"total"`
}

type ListItemWeeklyWindowsAPIResponse struct {
	Windows []ItemWeeklyWindowResponse `json:"windows"`
}

type ListOrganizationUnitsRequest struct {
	UnitType string `form:"unit_type"`
	ParentID string `form:"parent_id"`
	Status   string `form:"status,optional"`
}

type ListOrganizationUnitsResponse struct {
	Items []AdminOrganizationUnitResponse `json:"items"`
}

type ListRoomExaminationItemsAPIRequest struct {
	RoomID   string `path:"roomId"`
	Status   string `form:"status,optional"`
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"page_size,default=20"`
}

type ListRoomExaminationItemsAPIResponse struct {
	Relations []RoomExaminationItemResponse `json:"relations"`
	Page      int64                         `json:"page"`
	PageSize  int64                         `json:"page_size"`
	Total     int64                         `json:"total"`
}

type ListRoomWeeklyWindowsAPIResponse struct {
	Windows []RoomWeeklyWindowResponse `json:"windows"`
}

type OrganizationContextResponse struct {
	Hospital HospitalSummaryResponse `json:"hospital"`
	Campuses []CampusSummaryResponse `json:"campuses"`
}

type OrganizationUnitPathRequest struct {
	UnitID string `path:"unitId"`
}

type PhoneBindingResponse struct {
	PhoneMasked        string `json:"phone_masked"`
	VerificationStatus string `json:"verification_status"`
	VerificationSource string `json:"verification_source"`
}

type PhoneLoginRequest struct {
	Phone            string `json:"phone"`
	VerificationCode string `json:"verification_code"`
}

type PromoteDoctorRequest struct {
	AccountID         string  `path:"accountId"`
	DepartmentID      string  `json:"department_id"`
	DisplayName       string  `json:"display_name"`
	StaffNo           *string `json:"staff_no,optional"`
	AvatarURL         *string `json:"avatar_url,optional"`
	Description       *string `json:"description,optional"`
	ManagementVersion int64   `json:"management_version"`
	OfflineVerified   bool    `json:"offline_verified"`
	OperationID       string  `json:"operation_id"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RevokeTokenResponse struct {
	Revoked bool `json:"revoked"`
}

type RoomExaminationItemResponse struct {
	RelationID      string `json:"relation_id"`
	RoomID          string `json:"room_id"`
	ItemID          string `json:"item_id"`
	RoomDisplayName string `json:"room_display_name"`
	CampusID        string `json:"campus_id"`
	Building        string `json:"building"`
	FloorNumber     int32  `json:"floor_number"`
	RoomNumber      string `json:"room_number"`
	ItemName        string `json:"item_name"`
	Status          string `json:"status"`
	Version         int64  `json:"version"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type RoomWeeklyWindowResponse struct {
	WindowID       string `json:"window_id"`
	RoomID         string `json:"room_id"`
	Weekday        int32  `json:"weekday"`
	Session        string `json:"session"`
	OpenTime       string `json:"open_time"`
	CloseTime      string `json:"close_time"`
	ActiveCapacity int64  `json:"active_capacity"`
	Status         string `json:"status"`
	Version        int64  `json:"version"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type SendPhoneLoginCodeRequest struct {
	Phone string `json:"phone"`
}

type SendPhoneLoginCodeResponse struct {
	Accepted          bool  `json:"accepted"`
	RetryAfterSeconds int64 `json:"retry_after_seconds"`
}

type SetItemWeeklyWindowAPIRequest struct {
	ItemID            string `path:"itemId"`
	WindowID          string `json:"window_id,optional"`
	Weekday           int32  `json:"weekday"`
	Session           string `json:"session"`
	StartTime         string `json:"start_time"`
	BookingCutoffTime string `json:"booking_cutoff_time"`
	EndTime           string `json:"end_time"`
	ExpectedVersion   int64  `json:"expected_version"`
	OperationID       string `json:"operation_id"`
}

type SetPhoneRequest struct {
	Phone string `json:"phone"`
}

type SetRoomWeeklyWindowAPIRequest struct {
	RoomID          string `path:"roomId"`
	WindowID        string `json:"window_id,optional"`
	Weekday         int32  `json:"weekday"`
	Session         string `json:"session"`
	OpenTime        string `json:"open_time"`
	CloseTime       string `json:"close_time"`
	ActiveCapacity  int64  `json:"active_capacity"`
	ExpectedVersion int64  `json:"expected_version"`
	OperationID     string `json:"operation_id"`
}

type TokenResponse struct {
	AccessToken             string `json:"access_token"`
	RefreshToken            string `json:"refresh_token"`
	AccessExpiresInSeconds  int64  `json:"access_expires_in_seconds"`
	RefreshExpiresInSeconds int64  `json:"refresh_expires_in_seconds"`
}

type UpdateAccountDisplayProfileRequest struct {
	Nickname string `json:"nickname"`
}

type UpdateAppointmentRoomRequest struct {
	RoomID          string `path:"roomId"`
	CampusID        string `json:"campus_id"`
	Building        string `json:"building"`
	FloorNumber     int32  `json:"floor_number"`
	RoomNumber      string `json:"room_number"`
	ExpectedVersion int64  `json:"expected_version"`
	OperationID     string `json:"operation_id"`
}

type UpdateDoctorRequest struct {
	AccountID         string  `path:"accountId"`
	DisplayName       *string `json:"display_name,optional"`
	StaffNo           *string `json:"staff_no,optional"`
	AvatarURL         *string `json:"avatar_url,optional"`
	Description       *string `json:"description,optional"`
	ManagementVersion int64   `json:"management_version"`
	OperationID       string  `json:"operation_id"`
}

type UpdateExaminationItemRequest struct {
	ItemID          string  `path:"itemId"`
	Name            *string `json:"name,optional"`
	Description     *string `json:"description,optional"`
	ExpectedVersion int64   `json:"expected_version"`
	OperationID     string  `json:"operation_id"`
}

type UpdateOrganizationUnitRequest struct {
	UnitID      string  `path:"unitId"`
	Name        *string `json:"name,optional"`
	ParentID    *string `json:"parent_id,optional"`
	Version     int64   `json:"version"`
	OperationID string  `json:"operation_id"`
}

type WeChatLoginRequest struct {
	LoginCode string `json:"login_code"`
}

type WeeklyWindowsPathRequest struct {
	ResourceID string `path:"resourceId"`
}
