// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: appointment.proto

package server

import (
	"context"

	"hospital/contracts/gen/appointment/v1"
	"hospital/service/appointment/rpc/internal/logic"
	"hospital/service/appointment/rpc/internal/svc"
)

type AppointmentServiceServer struct {
	svcCtx *svc.ServiceContext
	appointmentv1.UnimplementedAppointmentServiceServer
}

func NewAppointmentServiceServer(svcCtx *svc.ServiceContext) *AppointmentServiceServer {
	return &AppointmentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AppointmentServiceServer) CreateExaminationItem(ctx context.Context, in *appointmentv1.CreateExaminationItemRequest) (*appointmentv1.ExaminationItem, error) {
	l := logic.NewCreateExaminationItemLogic(ctx, s.svcCtx)
	return l.CreateExaminationItem(in)
}

func (s *AppointmentServiceServer) GetExaminationItem(ctx context.Context, in *appointmentv1.GetExaminationItemRequest) (*appointmentv1.ExaminationItem, error) {
	l := logic.NewGetExaminationItemLogic(ctx, s.svcCtx)
	return l.GetExaminationItem(in)
}

func (s *AppointmentServiceServer) ListExaminationItems(ctx context.Context, in *appointmentv1.ListExaminationItemsRequest) (*appointmentv1.ListExaminationItemsResponse, error) {
	l := logic.NewListExaminationItemsLogic(ctx, s.svcCtx)
	return l.ListExaminationItems(in)
}

func (s *AppointmentServiceServer) UpdateExaminationItem(ctx context.Context, in *appointmentv1.UpdateExaminationItemRequest) (*appointmentv1.ExaminationItem, error) {
	l := logic.NewUpdateExaminationItemLogic(ctx, s.svcCtx)
	return l.UpdateExaminationItem(in)
}

func (s *AppointmentServiceServer) DisableExaminationItem(ctx context.Context, in *appointmentv1.ChangeExaminationItemStatusRequest) (*appointmentv1.ExaminationItem, error) {
	l := logic.NewDisableExaminationItemLogic(ctx, s.svcCtx)
	return l.DisableExaminationItem(in)
}

func (s *AppointmentServiceServer) EnableExaminationItem(ctx context.Context, in *appointmentv1.ChangeExaminationItemStatusRequest) (*appointmentv1.ExaminationItem, error) {
	l := logic.NewEnableExaminationItemLogic(ctx, s.svcCtx)
	return l.EnableExaminationItem(in)
}

func (s *AppointmentServiceServer) CreateRoom(ctx context.Context, in *appointmentv1.CreateRoomRequest) (*appointmentv1.Room, error) {
	l := logic.NewCreateRoomLogic(ctx, s.svcCtx)
	return l.CreateRoom(in)
}

func (s *AppointmentServiceServer) GetRoom(ctx context.Context, in *appointmentv1.GetRoomRequest) (*appointmentv1.Room, error) {
	l := logic.NewGetRoomLogic(ctx, s.svcCtx)
	return l.GetRoom(in)
}

func (s *AppointmentServiceServer) ListRooms(ctx context.Context, in *appointmentv1.ListRoomsRequest) (*appointmentv1.ListRoomsResponse, error) {
	l := logic.NewListRoomsLogic(ctx, s.svcCtx)
	return l.ListRooms(in)
}

func (s *AppointmentServiceServer) UpdateRoom(ctx context.Context, in *appointmentv1.UpdateRoomRequest) (*appointmentv1.Room, error) {
	l := logic.NewUpdateRoomLogic(ctx, s.svcCtx)
	return l.UpdateRoom(in)
}

func (s *AppointmentServiceServer) RetireRoom(ctx context.Context, in *appointmentv1.RetireRoomRequest) (*appointmentv1.Room, error) {
	l := logic.NewRetireRoomLogic(ctx, s.svcCtx)
	return l.RetireRoom(in)
}

func (s *AppointmentServiceServer) AddRoomExaminationItem(ctx context.Context, in *appointmentv1.AddRoomExaminationItemRequest) (*appointmentv1.RoomExaminationItem, error) {
	l := logic.NewAddRoomExaminationItemLogic(ctx, s.svcCtx)
	return l.AddRoomExaminationItem(in)
}

func (s *AppointmentServiceServer) DisableRoomExaminationItem(ctx context.Context, in *appointmentv1.ChangeResourceStatusRequest) (*appointmentv1.RoomExaminationItem, error) {
	l := logic.NewDisableRoomExaminationItemLogic(ctx, s.svcCtx)
	return l.DisableRoomExaminationItem(in)
}

func (s *AppointmentServiceServer) EnableRoomExaminationItem(ctx context.Context, in *appointmentv1.ChangeResourceStatusRequest) (*appointmentv1.RoomExaminationItem, error) {
	l := logic.NewEnableRoomExaminationItemLogic(ctx, s.svcCtx)
	return l.EnableRoomExaminationItem(in)
}

func (s *AppointmentServiceServer) ListRoomExaminationItems(ctx context.Context, in *appointmentv1.ListRoomExaminationItemsRequest) (*appointmentv1.ListRoomExaminationItemsResponse, error) {
	l := logic.NewListRoomExaminationItemsLogic(ctx, s.svcCtx)
	return l.ListRoomExaminationItems(in)
}

func (s *AppointmentServiceServer) ListAvailableRoomsByExaminationItem(ctx context.Context, in *appointmentv1.ListAvailableRoomsByExaminationItemRequest) (*appointmentv1.ListRoomExaminationItemsResponse, error) {
	l := logic.NewListAvailableRoomsByExaminationItemLogic(ctx, s.svcCtx)
	return l.ListAvailableRoomsByExaminationItem(in)
}

func (s *AppointmentServiceServer) SetRoomWeeklyWindow(ctx context.Context, in *appointmentv1.SetRoomWeeklyWindowRequest) (*appointmentv1.RoomWeeklyWindow, error) {
	l := logic.NewSetRoomWeeklyWindowLogic(ctx, s.svcCtx)
	return l.SetRoomWeeklyWindow(in)
}

func (s *AppointmentServiceServer) DisableRoomWeeklyWindow(ctx context.Context, in *appointmentv1.ChangeResourceStatusRequest) (*appointmentv1.RoomWeeklyWindow, error) {
	l := logic.NewDisableRoomWeeklyWindowLogic(ctx, s.svcCtx)
	return l.DisableRoomWeeklyWindow(in)
}

func (s *AppointmentServiceServer) ListRoomWeeklyWindows(ctx context.Context, in *appointmentv1.ListWeeklyWindowsRequest) (*appointmentv1.ListRoomWeeklyWindowsResponse, error) {
	l := logic.NewListRoomWeeklyWindowsLogic(ctx, s.svcCtx)
	return l.ListRoomWeeklyWindows(in)
}

func (s *AppointmentServiceServer) SetItemWeeklyWindow(ctx context.Context, in *appointmentv1.SetItemWeeklyWindowRequest) (*appointmentv1.ItemWeeklyWindow, error) {
	l := logic.NewSetItemWeeklyWindowLogic(ctx, s.svcCtx)
	return l.SetItemWeeklyWindow(in)
}

func (s *AppointmentServiceServer) DisableItemWeeklyWindow(ctx context.Context, in *appointmentv1.ChangeResourceStatusRequest) (*appointmentv1.ItemWeeklyWindow, error) {
	l := logic.NewDisableItemWeeklyWindowLogic(ctx, s.svcCtx)
	return l.DisableItemWeeklyWindow(in)
}

func (s *AppointmentServiceServer) ListItemWeeklyWindows(ctx context.Context, in *appointmentv1.ListWeeklyWindowsRequest) (*appointmentv1.ListItemWeeklyWindowsResponse, error) {
	l := logic.NewListItemWeeklyWindowsLogic(ctx, s.svcCtx)
	return l.ListItemWeeklyWindows(in)
}
