// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: guidance.proto

package guidanceservice

import (
	"context"

	v1_guidancev1 "hospital/contracts/gen/guidance/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePrecedenceRuleRequest  = v1_guidancev1.CreatePrecedenceRuleRequest
	DeletePrecedenceRuleRequest  = v1_guidancev1.DeletePrecedenceRuleRequest
	DeletePrecedenceRuleResponse = v1_guidancev1.DeletePrecedenceRuleResponse
	ListPrecedenceRulesRequest   = v1_guidancev1.ListPrecedenceRulesRequest
	ListPrecedenceRulesResponse  = v1_guidancev1.ListPrecedenceRulesResponse
	PrecedenceRule               = v1_guidancev1.PrecedenceRule
	UpdatePrecedenceRuleRequest  = v1_guidancev1.UpdatePrecedenceRuleRequest

	GuidanceService interface {
		CreatePrecedenceRule(ctx context.Context, in *CreatePrecedenceRuleRequest, opts ...grpc.CallOption) (*PrecedenceRule, error)
		UpdatePrecedenceRule(ctx context.Context, in *UpdatePrecedenceRuleRequest, opts ...grpc.CallOption) (*PrecedenceRule, error)
		DeletePrecedenceRule(ctx context.Context, in *DeletePrecedenceRuleRequest, opts ...grpc.CallOption) (*DeletePrecedenceRuleResponse, error)
		ListPrecedenceRules(ctx context.Context, in *ListPrecedenceRulesRequest, opts ...grpc.CallOption) (*ListPrecedenceRulesResponse, error)
	}

	defaultGuidanceService struct {
		cli zrpc.Client
	}
)

func NewGuidanceService(cli zrpc.Client) GuidanceService {
	return &defaultGuidanceService{
		cli: cli,
	}
}

func (m *defaultGuidanceService) CreatePrecedenceRule(ctx context.Context, in *CreatePrecedenceRuleRequest, opts ...grpc.CallOption) (*PrecedenceRule, error) {
	client := v1_guidancev1.NewGuidanceServiceClient(m.cli.Conn())
	return client.CreatePrecedenceRule(ctx, in, opts...)
}

func (m *defaultGuidanceService) UpdatePrecedenceRule(ctx context.Context, in *UpdatePrecedenceRuleRequest, opts ...grpc.CallOption) (*PrecedenceRule, error) {
	client := v1_guidancev1.NewGuidanceServiceClient(m.cli.Conn())
	return client.UpdatePrecedenceRule(ctx, in, opts...)
}

func (m *defaultGuidanceService) DeletePrecedenceRule(ctx context.Context, in *DeletePrecedenceRuleRequest, opts ...grpc.CallOption) (*DeletePrecedenceRuleResponse, error) {
	client := v1_guidancev1.NewGuidanceServiceClient(m.cli.Conn())
	return client.DeletePrecedenceRule(ctx, in, opts...)
}

func (m *defaultGuidanceService) ListPrecedenceRules(ctx context.Context, in *ListPrecedenceRulesRequest, opts ...grpc.CallOption) (*ListPrecedenceRulesResponse, error) {
	client := v1_guidancev1.NewGuidanceServiceClient(m.cli.Conn())
	return client.ListPrecedenceRules(ctx, in, opts...)
}
