// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	appointmentcatalog "hospital/service/app/api/internal/handler/appointmentcatalog"
	appointmentresources "hospital/service/app/api/internal/handler/appointmentresources"
	auth "hospital/service/app/api/internal/handler/auth"
	identityadmin "hospital/service/app/api/internal/handler/identityadmin"
	identityprofile "hospital/service/app/api/internal/handler/identityprofile"
	organizationadmin "hospital/service/app/api/internal/handler/organizationadmin"
	organizationdirectory "hospital/service/app/api/internal/handler/organizationdirectory"
	system "hospital/service/app/api/internal/handler/system"
	"hospital/service/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessToken},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/admin/appointment/examination-items",
					Handler: appointmentcatalog.ListExaminationItemsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/appointment/examination-items",
					Handler: appointmentcatalog.CreateExaminationItemHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/appointment/examination-items/:itemId",
					Handler: appointmentcatalog.GetExaminationItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/appointment/examination-items/:itemId",
					Handler: appointmentcatalog.UpdateExaminationItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/appointment/examination-items/:itemId/disable",
					Handler: appointmentcatalog.DisableExaminationItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/appointment/examination-items/:itemId/enable",
					Handler: appointmentcatalog.EnableExaminationItemHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessToken},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/admin/appointment/examination-items/:itemId/weekly-window",
					Handler: appointmentresources.SetItemWeeklyWindowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/appointment/examination-items/:resourceId/weekly-windows",
					Handler: appointmentresources.ListItemWeeklyWindowsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/appointment/item-weekly-windows/:resourceId/disable",
					Handler: appointmentresources.DisableItemWeeklyWindowHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/appointment/room-examination-items/:resourceId/disable",
					Handler: appointmentresources.DisableRoomExaminationItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/appointment/room-examination-items/:resourceId/enable",
					Handler: appointmentresources.EnableRoomExaminationItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/appointment/room-weekly-windows/:resourceId/disable",
					Handler: appointmentresources.DisableRoomWeeklyWindowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/appointment/rooms",
					Handler: appointmentresources.ListAppointmentRoomsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/appointment/rooms",
					Handler: appointmentresources.CreateAppointmentRoomHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/appointment/rooms/:resourceId/disable",
					Handler: appointmentresources.DisableAppointmentRoomHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/appointment/rooms/:resourceId/enable",
					Handler: appointmentresources.EnableAppointmentRoomHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/appointment/rooms/:resourceId/weekly-windows",
					Handler: appointmentresources.ListRoomWeeklyWindowsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/appointment/rooms/:roomId",
					Handler: appointmentresources.GetAppointmentRoomHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/appointment/rooms/:roomId",
					Handler: appointmentresources.UpdateAppointmentRoomHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/appointment/rooms/:roomId/examination-items",
					Handler: appointmentresources.ListRoomExaminationItemsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/appointment/rooms/:roomId/examination-items",
					Handler: appointmentresources.AddRoomExaminationItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/appointment/rooms/:roomId/weekly-window",
					Handler: appointmentresources.SetRoomWeeklyWindowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/appointment/examination-items/:itemId/rooms",
					Handler: appointmentresources.ListAvailableRoomsByExaminationItemHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/phone/code",
				Handler: auth.SendPhoneLoginCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/phone/login",
				Handler: auth.PhoneLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/wechat/login",
				Handler: auth.WeChatLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessToken},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/auth/me",
					Handler: auth.CurrentIdentityHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/auth/me/phone",
					Handler: auth.SetMyPhoneHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/token/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/token/revoke",
				Handler: auth.RevokeTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessToken},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/admin/identity/accounts",
					Handler: identityadmin.ListAdminAccountsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/identity/accounts/:accountId",
					Handler: identityadmin.GetAdminAccountHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/identity/accounts/:accountId/disable",
					Handler: identityadmin.DisableAccountHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/identity/accounts/:accountId/enable",
					Handler: identityadmin.EnableAccountHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/identity/accounts/:accountId/promote-doctor",
					Handler: identityadmin.PromoteDoctorHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/identity/accounts/search-by-phone",
					Handler: identityadmin.SearchAdminAccountByPhoneHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/identity/doctors/:accountId",
					Handler: identityadmin.UpdateDoctorHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/identity/doctors/:accountId/department",
					Handler: identityadmin.ChangeDoctorDepartmentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/identity/doctors/:accountId/revoke",
					Handler: identityadmin.RevokeDoctorHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessToken},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/auth/me/display-profile",
					Handler: identityprofile.GetAccountDisplayProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/auth/me/display-profile",
					Handler: identityprofile.UpdateAccountDisplayProfileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessToken},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/admin/identity/organization-units",
					Handler: organizationadmin.ListOrganizationUnitsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/identity/organization-units",
					Handler: organizationadmin.CreateOrganizationUnitHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/identity/organization-units/:unitId",
					Handler: organizationadmin.GetOrganizationUnitHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/identity/organization-units/:unitId",
					Handler: organizationadmin.UpdateOrganizationUnitHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/identity/organization-units/:unitId/disable",
					Handler: organizationadmin.DisableOrganizationUnitHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/identity/organization-units/:unitId/enable",
					Handler: organizationadmin.EnableOrganizationUnitHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/directory/departments/:departmentId/doctors",
				Handler: organizationdirectory.ListDoctorsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/directory/departments",
				Handler: organizationdirectory.ListDepartmentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/directory/organization-context",
				Handler: organizationdirectory.GetOrganizationContextHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: system.HealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
