// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: appointment.proto

package appointmentservice

import (
	"context"

	"hospital/contracts/gen/appointment/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddRoomExaminationItemRequest              = appointmentv1.AddRoomExaminationItemRequest
	ChangeExaminationItemStatusRequest         = appointmentv1.ChangeExaminationItemStatusRequest
	ChangeResourceStatusRequest                = appointmentv1.ChangeResourceStatusRequest
	CreateExaminationItemRequest               = appointmentv1.CreateExaminationItemRequest
	CreateRoomRequest                          = appointmentv1.CreateRoomRequest
	ExaminationItem                            = appointmentv1.ExaminationItem
	ExaminationItemInput                       = appointmentv1.ExaminationItemInput
	GetExaminationItemRequest                  = appointmentv1.GetExaminationItemRequest
	GetRoomRequest                             = appointmentv1.GetRoomRequest
	ItemWeeklyWindow                           = appointmentv1.ItemWeeklyWindow
	ListAvailableRoomsByExaminationItemRequest = appointmentv1.ListAvailableRoomsByExaminationItemRequest
	ListExaminationItemsRequest                = appointmentv1.ListExaminationItemsRequest
	ListExaminationItemsResponse               = appointmentv1.ListExaminationItemsResponse
	ListItemWeeklyWindowsResponse              = appointmentv1.ListItemWeeklyWindowsResponse
	ListRoomExaminationItemsRequest            = appointmentv1.ListRoomExaminationItemsRequest
	ListRoomExaminationItemsResponse           = appointmentv1.ListRoomExaminationItemsResponse
	ListRoomWeeklyWindowsResponse              = appointmentv1.ListRoomWeeklyWindowsResponse
	ListRoomsRequest                           = appointmentv1.ListRoomsRequest
	ListRoomsResponse                          = appointmentv1.ListRoomsResponse
	ListWeeklyWindowsRequest                   = appointmentv1.ListWeeklyWindowsRequest
	Room                                       = appointmentv1.Room
	RoomExaminationItem                        = appointmentv1.RoomExaminationItem
	RoomWeeklyWindow                           = appointmentv1.RoomWeeklyWindow
	SetItemWeeklyWindowRequest                 = appointmentv1.SetItemWeeklyWindowRequest
	SetRoomWeeklyWindowRequest                 = appointmentv1.SetRoomWeeklyWindowRequest
	UpdateExaminationItemRequest               = appointmentv1.UpdateExaminationItemRequest
	UpdateRoomRequest                          = appointmentv1.UpdateRoomRequest

	AppointmentService interface {
		CreateExaminationItem(ctx context.Context, in *CreateExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error)
		GetExaminationItem(ctx context.Context, in *GetExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error)
		ListExaminationItems(ctx context.Context, in *ListExaminationItemsRequest, opts ...grpc.CallOption) (*ListExaminationItemsResponse, error)
		UpdateExaminationItem(ctx context.Context, in *UpdateExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error)
		DisableExaminationItem(ctx context.Context, in *ChangeExaminationItemStatusRequest, opts ...grpc.CallOption) (*ExaminationItem, error)
		EnableExaminationItem(ctx context.Context, in *ChangeExaminationItemStatusRequest, opts ...grpc.CallOption) (*ExaminationItem, error)
		CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Room, error)
		GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error)
		ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error)
		UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*Room, error)
		DisableRoom(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*Room, error)
		EnableRoom(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*Room, error)
		AddRoomExaminationItem(ctx context.Context, in *AddRoomExaminationItemRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error)
		DisableRoomExaminationItem(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error)
		EnableRoomExaminationItem(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error)
		ListRoomExaminationItems(ctx context.Context, in *ListRoomExaminationItemsRequest, opts ...grpc.CallOption) (*ListRoomExaminationItemsResponse, error)
		ListAvailableRoomsByExaminationItem(ctx context.Context, in *ListAvailableRoomsByExaminationItemRequest, opts ...grpc.CallOption) (*ListRoomExaminationItemsResponse, error)
		SetRoomWeeklyWindow(ctx context.Context, in *SetRoomWeeklyWindowRequest, opts ...grpc.CallOption) (*RoomWeeklyWindow, error)
		DisableRoomWeeklyWindow(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomWeeklyWindow, error)
		ListRoomWeeklyWindows(ctx context.Context, in *ListWeeklyWindowsRequest, opts ...grpc.CallOption) (*ListRoomWeeklyWindowsResponse, error)
		SetItemWeeklyWindow(ctx context.Context, in *SetItemWeeklyWindowRequest, opts ...grpc.CallOption) (*ItemWeeklyWindow, error)
		DisableItemWeeklyWindow(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*ItemWeeklyWindow, error)
		ListItemWeeklyWindows(ctx context.Context, in *ListWeeklyWindowsRequest, opts ...grpc.CallOption) (*ListItemWeeklyWindowsResponse, error)
	}

	defaultAppointmentService struct {
		cli zrpc.Client
	}
)

func NewAppointmentService(cli zrpc.Client) AppointmentService {
	return &defaultAppointmentService{
		cli: cli,
	}
}

func (m *defaultAppointmentService) CreateExaminationItem(ctx context.Context, in *CreateExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.CreateExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) GetExaminationItem(ctx context.Context, in *GetExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.GetExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListExaminationItems(ctx context.Context, in *ListExaminationItemsRequest, opts ...grpc.CallOption) (*ListExaminationItemsResponse, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListExaminationItems(ctx, in, opts...)
}

func (m *defaultAppointmentService) UpdateExaminationItem(ctx context.Context, in *UpdateExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.UpdateExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) DisableExaminationItem(ctx context.Context, in *ChangeExaminationItemStatusRequest, opts ...grpc.CallOption) (*ExaminationItem, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.DisableExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) EnableExaminationItem(ctx context.Context, in *ChangeExaminationItemStatusRequest, opts ...grpc.CallOption) (*ExaminationItem, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.EnableExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.CreateRoom(ctx, in, opts...)
}

func (m *defaultAppointmentService) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.GetRoom(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListRooms(ctx, in, opts...)
}

func (m *defaultAppointmentService) UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.UpdateRoom(ctx, in, opts...)
}

func (m *defaultAppointmentService) DisableRoom(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*Room, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.DisableRoom(ctx, in, opts...)
}

func (m *defaultAppointmentService) EnableRoom(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*Room, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.EnableRoom(ctx, in, opts...)
}

func (m *defaultAppointmentService) AddRoomExaminationItem(ctx context.Context, in *AddRoomExaminationItemRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.AddRoomExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) DisableRoomExaminationItem(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.DisableRoomExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) EnableRoomExaminationItem(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.EnableRoomExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListRoomExaminationItems(ctx context.Context, in *ListRoomExaminationItemsRequest, opts ...grpc.CallOption) (*ListRoomExaminationItemsResponse, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListRoomExaminationItems(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListAvailableRoomsByExaminationItem(ctx context.Context, in *ListAvailableRoomsByExaminationItemRequest, opts ...grpc.CallOption) (*ListRoomExaminationItemsResponse, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListAvailableRoomsByExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) SetRoomWeeklyWindow(ctx context.Context, in *SetRoomWeeklyWindowRequest, opts ...grpc.CallOption) (*RoomWeeklyWindow, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.SetRoomWeeklyWindow(ctx, in, opts...)
}

func (m *defaultAppointmentService) DisableRoomWeeklyWindow(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomWeeklyWindow, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.DisableRoomWeeklyWindow(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListRoomWeeklyWindows(ctx context.Context, in *ListWeeklyWindowsRequest, opts ...grpc.CallOption) (*ListRoomWeeklyWindowsResponse, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListRoomWeeklyWindows(ctx, in, opts...)
}

func (m *defaultAppointmentService) SetItemWeeklyWindow(ctx context.Context, in *SetItemWeeklyWindowRequest, opts ...grpc.CallOption) (*ItemWeeklyWindow, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.SetItemWeeklyWindow(ctx, in, opts...)
}

func (m *defaultAppointmentService) DisableItemWeeklyWindow(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*ItemWeeklyWindow, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.DisableItemWeeklyWindow(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListItemWeeklyWindows(ctx context.Context, in *ListWeeklyWindowsRequest, opts ...grpc.CallOption) (*ListItemWeeklyWindowsResponse, error) {
	client := appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListItemWeeklyWindows(ctx, in, opts...)
}
