// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: appointment.proto

package appointmentservice

import (
	"context"

	v1_appointmentv1 "hospital/contracts/gen/appointment/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddRoomExaminationItemRequest              = v1_appointmentv1.AddRoomExaminationItemRequest
	Booking                                    = v1_appointmentv1.Booking
	BookingOption                              = v1_appointmentv1.BookingOption
	ChangeExaminationItemStatusRequest         = v1_appointmentv1.ChangeExaminationItemStatusRequest
	ChangeResourceStatusRequest                = v1_appointmentv1.ChangeResourceStatusRequest
	CompleteAndPublishExaminationReportRequest = v1_appointmentv1.CompleteAndPublishExaminationReportRequest
	CorrectExaminationReportRequest            = v1_appointmentv1.CorrectExaminationReportRequest
	CreateBookingRequest                       = v1_appointmentv1.CreateBookingRequest
	CreateExaminationItemRequest               = v1_appointmentv1.CreateExaminationItemRequest
	CreateRoomRequest                          = v1_appointmentv1.CreateRoomRequest
	DeleteBookingRequest                       = v1_appointmentv1.DeleteBookingRequest
	DeleteBookingResponse                      = v1_appointmentv1.DeleteBookingResponse
	DepartmentUnreadCount                      = v1_appointmentv1.DepartmentUnreadCount
	ExaminationItem                            = v1_appointmentv1.ExaminationItem
	ExaminationItemInput                       = v1_appointmentv1.ExaminationItemInput
	ExaminationItemReportTemplate              = v1_appointmentv1.ExaminationItemReportTemplate
	ExaminationReport                          = v1_appointmentv1.ExaminationReport
	ExaminationReportContent                   = v1_appointmentv1.ExaminationReportContent
	ExaminationReportVersion                   = v1_appointmentv1.ExaminationReportVersion
	GetBookingRequest                          = v1_appointmentv1.GetBookingRequest
	GetExaminationItemRequest                  = v1_appointmentv1.GetExaminationItemRequest
	GetExaminationReportRequest                = v1_appointmentv1.GetExaminationReportRequest
	GetRoomRequest                             = v1_appointmentv1.GetRoomRequest
	ItemWeeklyWindow                           = v1_appointmentv1.ItemWeeklyWindow
	ListAvailableRoomsByExaminationItemRequest = v1_appointmentv1.ListAvailableRoomsByExaminationItemRequest
	ListBookingOptionsRequest                  = v1_appointmentv1.ListBookingOptionsRequest
	ListBookingOptionsResponse                 = v1_appointmentv1.ListBookingOptionsResponse
	ListBookingsRequest                        = v1_appointmentv1.ListBookingsRequest
	ListBookingsResponse                       = v1_appointmentv1.ListBookingsResponse
	ListExaminationItemsRequest                = v1_appointmentv1.ListExaminationItemsRequest
	ListExaminationItemsResponse               = v1_appointmentv1.ListExaminationItemsResponse
	ListExaminationReportVersionsRequest       = v1_appointmentv1.ListExaminationReportVersionsRequest
	ListExaminationReportVersionsResponse      = v1_appointmentv1.ListExaminationReportVersionsResponse
	ListExaminationReportsRequest              = v1_appointmentv1.ListExaminationReportsRequest
	ListExaminationReportsResponse             = v1_appointmentv1.ListExaminationReportsResponse
	ListItemWeeklyWindowsResponse              = v1_appointmentv1.ListItemWeeklyWindowsResponse
	ListMessagesRequest                        = v1_appointmentv1.ListMessagesRequest
	ListMessagesResponse                       = v1_appointmentv1.ListMessagesResponse
	ListMyBookingsRequest                      = v1_appointmentv1.ListMyBookingsRequest
	ListMyExaminationReportsRequest            = v1_appointmentv1.ListMyExaminationReportsRequest
	ListMyMessagesRequest                      = v1_appointmentv1.ListMyMessagesRequest
	ListRoomExaminationItemsRequest            = v1_appointmentv1.ListRoomExaminationItemsRequest
	ListRoomExaminationItemsResponse           = v1_appointmentv1.ListRoomExaminationItemsResponse
	ListRoomWeeklyWindowsResponse              = v1_appointmentv1.ListRoomWeeklyWindowsResponse
	ListRoomsRequest                           = v1_appointmentv1.ListRoomsRequest
	ListRoomsResponse                          = v1_appointmentv1.ListRoomsResponse
	ListWeeklyWindowsRequest                   = v1_appointmentv1.ListWeeklyWindowsRequest
	MarkMessageReadRequest                     = v1_appointmentv1.MarkMessageReadRequest
	Message                                    = v1_appointmentv1.Message
	RetireRoomRequest                          = v1_appointmentv1.RetireRoomRequest
	Room                                       = v1_appointmentv1.Room
	RoomExaminationItem                        = v1_appointmentv1.RoomExaminationItem
	RoomWeeklyWindow                           = v1_appointmentv1.RoomWeeklyWindow
	SaveExaminationItemReportTemplateRequest   = v1_appointmentv1.SaveExaminationItemReportTemplateRequest
	SaveExaminationReportDraftRequest          = v1_appointmentv1.SaveExaminationReportDraftRequest
	SetItemWeeklyWindowRequest                 = v1_appointmentv1.SetItemWeeklyWindowRequest
	SetRoomWeeklyWindowRequest                 = v1_appointmentv1.SetRoomWeeklyWindowRequest
	StartExaminationRequest                    = v1_appointmentv1.StartExaminationRequest
	UpdateExaminationItemRequest               = v1_appointmentv1.UpdateExaminationItemRequest
	UpdateRoomRequest                          = v1_appointmentv1.UpdateRoomRequest

	AppointmentService interface {
		CreateExaminationItem(ctx context.Context, in *CreateExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error)
		GetExaminationItem(ctx context.Context, in *GetExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error)
		ListExaminationItems(ctx context.Context, in *ListExaminationItemsRequest, opts ...grpc.CallOption) (*ListExaminationItemsResponse, error)
		UpdateExaminationItem(ctx context.Context, in *UpdateExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error)
		DisableExaminationItem(ctx context.Context, in *ChangeExaminationItemStatusRequest, opts ...grpc.CallOption) (*ExaminationItem, error)
		EnableExaminationItem(ctx context.Context, in *ChangeExaminationItemStatusRequest, opts ...grpc.CallOption) (*ExaminationItem, error)
		GetExaminationItemReportTemplate(ctx context.Context, in *GetExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItemReportTemplate, error)
		SaveExaminationItemReportTemplate(ctx context.Context, in *SaveExaminationItemReportTemplateRequest, opts ...grpc.CallOption) (*ExaminationItemReportTemplate, error)
		CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Room, error)
		GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error)
		ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error)
		UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*Room, error)
		RetireRoom(ctx context.Context, in *RetireRoomRequest, opts ...grpc.CallOption) (*Room, error)
		AddRoomExaminationItem(ctx context.Context, in *AddRoomExaminationItemRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error)
		DisableRoomExaminationItem(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error)
		EnableRoomExaminationItem(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error)
		ListRoomExaminationItems(ctx context.Context, in *ListRoomExaminationItemsRequest, opts ...grpc.CallOption) (*ListRoomExaminationItemsResponse, error)
		ListAvailableRoomsByExaminationItem(ctx context.Context, in *ListAvailableRoomsByExaminationItemRequest, opts ...grpc.CallOption) (*ListRoomExaminationItemsResponse, error)
		SetRoomWeeklyWindow(ctx context.Context, in *SetRoomWeeklyWindowRequest, opts ...grpc.CallOption) (*RoomWeeklyWindow, error)
		DisableRoomWeeklyWindow(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomWeeklyWindow, error)
		ListRoomWeeklyWindows(ctx context.Context, in *ListWeeklyWindowsRequest, opts ...grpc.CallOption) (*ListRoomWeeklyWindowsResponse, error)
		SetItemWeeklyWindow(ctx context.Context, in *SetItemWeeklyWindowRequest, opts ...grpc.CallOption) (*ItemWeeklyWindow, error)
		DisableItemWeeklyWindow(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*ItemWeeklyWindow, error)
		ListItemWeeklyWindows(ctx context.Context, in *ListWeeklyWindowsRequest, opts ...grpc.CallOption) (*ListItemWeeklyWindowsResponse, error)
		ListBookingOptions(ctx context.Context, in *ListBookingOptionsRequest, opts ...grpc.CallOption) (*ListBookingOptionsResponse, error)
		CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*Booking, error)
		GetMyBooking(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*Booking, error)
		ListMyBookings(ctx context.Context, in *ListMyBookingsRequest, opts ...grpc.CallOption) (*ListBookingsResponse, error)
		DeleteMyBooking(ctx context.Context, in *DeleteBookingRequest, opts ...grpc.CallOption) (*DeleteBookingResponse, error)
		ListMyMessages(ctx context.Context, in *ListMyMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
		MarkMyMessageRead(ctx context.Context, in *MarkMessageReadRequest, opts ...grpc.CallOption) (*Message, error)
		GetBooking(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*Booking, error)
		ListBookings(ctx context.Context, in *ListBookingsRequest, opts ...grpc.CallOption) (*ListBookingsResponse, error)
		StartExamination(ctx context.Context, in *StartExaminationRequest, opts ...grpc.CallOption) (*Booking, error)
		DeleteBooking(ctx context.Context, in *DeleteBookingRequest, opts ...grpc.CallOption) (*DeleteBookingResponse, error)
		ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
		MarkMessageRead(ctx context.Context, in *MarkMessageReadRequest, opts ...grpc.CallOption) (*Message, error)
		SaveExaminationReportDraft(ctx context.Context, in *SaveExaminationReportDraftRequest, opts ...grpc.CallOption) (*ExaminationReport, error)
		CompleteAndPublishExaminationReport(ctx context.Context, in *CompleteAndPublishExaminationReportRequest, opts ...grpc.CallOption) (*ExaminationReport, error)
		CorrectExaminationReport(ctx context.Context, in *CorrectExaminationReportRequest, opts ...grpc.CallOption) (*ExaminationReport, error)
		GetExaminationReport(ctx context.Context, in *GetExaminationReportRequest, opts ...grpc.CallOption) (*ExaminationReport, error)
		ListExaminationReports(ctx context.Context, in *ListExaminationReportsRequest, opts ...grpc.CallOption) (*ListExaminationReportsResponse, error)
		ListExaminationReportVersions(ctx context.Context, in *ListExaminationReportVersionsRequest, opts ...grpc.CallOption) (*ListExaminationReportVersionsResponse, error)
		GetMyExaminationReport(ctx context.Context, in *GetExaminationReportRequest, opts ...grpc.CallOption) (*ExaminationReport, error)
		ListMyExaminationReports(ctx context.Context, in *ListMyExaminationReportsRequest, opts ...grpc.CallOption) (*ListExaminationReportsResponse, error)
	}

	defaultAppointmentService struct {
		cli zrpc.Client
	}
)

func NewAppointmentService(cli zrpc.Client) AppointmentService {
	return &defaultAppointmentService{
		cli: cli,
	}
}

func (m *defaultAppointmentService) CreateExaminationItem(ctx context.Context, in *CreateExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.CreateExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) GetExaminationItem(ctx context.Context, in *GetExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.GetExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListExaminationItems(ctx context.Context, in *ListExaminationItemsRequest, opts ...grpc.CallOption) (*ListExaminationItemsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListExaminationItems(ctx, in, opts...)
}

func (m *defaultAppointmentService) UpdateExaminationItem(ctx context.Context, in *UpdateExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItem, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.UpdateExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) DisableExaminationItem(ctx context.Context, in *ChangeExaminationItemStatusRequest, opts ...grpc.CallOption) (*ExaminationItem, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.DisableExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) EnableExaminationItem(ctx context.Context, in *ChangeExaminationItemStatusRequest, opts ...grpc.CallOption) (*ExaminationItem, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.EnableExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) GetExaminationItemReportTemplate(ctx context.Context, in *GetExaminationItemRequest, opts ...grpc.CallOption) (*ExaminationItemReportTemplate, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.GetExaminationItemReportTemplate(ctx, in, opts...)
}

func (m *defaultAppointmentService) SaveExaminationItemReportTemplate(ctx context.Context, in *SaveExaminationItemReportTemplateRequest, opts ...grpc.CallOption) (*ExaminationItemReportTemplate, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.SaveExaminationItemReportTemplate(ctx, in, opts...)
}

func (m *defaultAppointmentService) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.CreateRoom(ctx, in, opts...)
}

func (m *defaultAppointmentService) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.GetRoom(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListRooms(ctx, in, opts...)
}

func (m *defaultAppointmentService) UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.UpdateRoom(ctx, in, opts...)
}

func (m *defaultAppointmentService) RetireRoom(ctx context.Context, in *RetireRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.RetireRoom(ctx, in, opts...)
}

func (m *defaultAppointmentService) AddRoomExaminationItem(ctx context.Context, in *AddRoomExaminationItemRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.AddRoomExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) DisableRoomExaminationItem(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.DisableRoomExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) EnableRoomExaminationItem(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomExaminationItem, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.EnableRoomExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListRoomExaminationItems(ctx context.Context, in *ListRoomExaminationItemsRequest, opts ...grpc.CallOption) (*ListRoomExaminationItemsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListRoomExaminationItems(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListAvailableRoomsByExaminationItem(ctx context.Context, in *ListAvailableRoomsByExaminationItemRequest, opts ...grpc.CallOption) (*ListRoomExaminationItemsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListAvailableRoomsByExaminationItem(ctx, in, opts...)
}

func (m *defaultAppointmentService) SetRoomWeeklyWindow(ctx context.Context, in *SetRoomWeeklyWindowRequest, opts ...grpc.CallOption) (*RoomWeeklyWindow, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.SetRoomWeeklyWindow(ctx, in, opts...)
}

func (m *defaultAppointmentService) DisableRoomWeeklyWindow(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*RoomWeeklyWindow, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.DisableRoomWeeklyWindow(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListRoomWeeklyWindows(ctx context.Context, in *ListWeeklyWindowsRequest, opts ...grpc.CallOption) (*ListRoomWeeklyWindowsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListRoomWeeklyWindows(ctx, in, opts...)
}

func (m *defaultAppointmentService) SetItemWeeklyWindow(ctx context.Context, in *SetItemWeeklyWindowRequest, opts ...grpc.CallOption) (*ItemWeeklyWindow, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.SetItemWeeklyWindow(ctx, in, opts...)
}

func (m *defaultAppointmentService) DisableItemWeeklyWindow(ctx context.Context, in *ChangeResourceStatusRequest, opts ...grpc.CallOption) (*ItemWeeklyWindow, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.DisableItemWeeklyWindow(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListItemWeeklyWindows(ctx context.Context, in *ListWeeklyWindowsRequest, opts ...grpc.CallOption) (*ListItemWeeklyWindowsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListItemWeeklyWindows(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListBookingOptions(ctx context.Context, in *ListBookingOptionsRequest, opts ...grpc.CallOption) (*ListBookingOptionsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListBookingOptions(ctx, in, opts...)
}

func (m *defaultAppointmentService) CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*Booking, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.CreateBooking(ctx, in, opts...)
}

func (m *defaultAppointmentService) GetMyBooking(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*Booking, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.GetMyBooking(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListMyBookings(ctx context.Context, in *ListMyBookingsRequest, opts ...grpc.CallOption) (*ListBookingsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListMyBookings(ctx, in, opts...)
}

func (m *defaultAppointmentService) DeleteMyBooking(ctx context.Context, in *DeleteBookingRequest, opts ...grpc.CallOption) (*DeleteBookingResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.DeleteMyBooking(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListMyMessages(ctx context.Context, in *ListMyMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListMyMessages(ctx, in, opts...)
}

func (m *defaultAppointmentService) MarkMyMessageRead(ctx context.Context, in *MarkMessageReadRequest, opts ...grpc.CallOption) (*Message, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.MarkMyMessageRead(ctx, in, opts...)
}

func (m *defaultAppointmentService) GetBooking(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*Booking, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.GetBooking(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListBookings(ctx context.Context, in *ListBookingsRequest, opts ...grpc.CallOption) (*ListBookingsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListBookings(ctx, in, opts...)
}

func (m *defaultAppointmentService) StartExamination(ctx context.Context, in *StartExaminationRequest, opts ...grpc.CallOption) (*Booking, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.StartExamination(ctx, in, opts...)
}

func (m *defaultAppointmentService) DeleteBooking(ctx context.Context, in *DeleteBookingRequest, opts ...grpc.CallOption) (*DeleteBookingResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.DeleteBooking(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListMessages(ctx, in, opts...)
}

func (m *defaultAppointmentService) MarkMessageRead(ctx context.Context, in *MarkMessageReadRequest, opts ...grpc.CallOption) (*Message, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.MarkMessageRead(ctx, in, opts...)
}

func (m *defaultAppointmentService) SaveExaminationReportDraft(ctx context.Context, in *SaveExaminationReportDraftRequest, opts ...grpc.CallOption) (*ExaminationReport, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.SaveExaminationReportDraft(ctx, in, opts...)
}

func (m *defaultAppointmentService) CompleteAndPublishExaminationReport(ctx context.Context, in *CompleteAndPublishExaminationReportRequest, opts ...grpc.CallOption) (*ExaminationReport, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.CompleteAndPublishExaminationReport(ctx, in, opts...)
}

func (m *defaultAppointmentService) CorrectExaminationReport(ctx context.Context, in *CorrectExaminationReportRequest, opts ...grpc.CallOption) (*ExaminationReport, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.CorrectExaminationReport(ctx, in, opts...)
}

func (m *defaultAppointmentService) GetExaminationReport(ctx context.Context, in *GetExaminationReportRequest, opts ...grpc.CallOption) (*ExaminationReport, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.GetExaminationReport(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListExaminationReports(ctx context.Context, in *ListExaminationReportsRequest, opts ...grpc.CallOption) (*ListExaminationReportsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListExaminationReports(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListExaminationReportVersions(ctx context.Context, in *ListExaminationReportVersionsRequest, opts ...grpc.CallOption) (*ListExaminationReportVersionsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListExaminationReportVersions(ctx, in, opts...)
}

func (m *defaultAppointmentService) GetMyExaminationReport(ctx context.Context, in *GetExaminationReportRequest, opts ...grpc.CallOption) (*ExaminationReport, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.GetMyExaminationReport(ctx, in, opts...)
}

func (m *defaultAppointmentService) ListMyExaminationReports(ctx context.Context, in *ListMyExaminationReportsRequest, opts ...grpc.CallOption) (*ListExaminationReportsResponse, error) {
	client := v1_appointmentv1.NewAppointmentServiceClient(m.cli.Conn())
	return client.ListMyExaminationReports(ctx, in, opts...)
}
