// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: guidance.proto

package server

import (
	"context"

	v1_guidancev1 "hospital/contracts/gen/guidance/v1"
	"hospital/service/guidance/rpc/internal/logic"
	"hospital/service/guidance/rpc/internal/svc"
)

type GuidanceServiceServer struct {
	svcCtx *svc.ServiceContext
	v1_guidancev1.UnimplementedGuidanceServiceServer
}

func NewGuidanceServiceServer(svcCtx *svc.ServiceContext) *GuidanceServiceServer {
	return &GuidanceServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GuidanceServiceServer) CreatePrecedenceRule(ctx context.Context, in *v1_guidancev1.CreatePrecedenceRuleRequest) (*v1_guidancev1.PrecedenceRule, error) {
	l := logic.NewCreatePrecedenceRuleLogic(ctx, s.svcCtx)
	return l.CreatePrecedenceRule(in)
}

func (s *GuidanceServiceServer) UpdatePrecedenceRule(ctx context.Context, in *v1_guidancev1.UpdatePrecedenceRuleRequest) (*v1_guidancev1.PrecedenceRule, error) {
	l := logic.NewUpdatePrecedenceRuleLogic(ctx, s.svcCtx)
	return l.UpdatePrecedenceRule(in)
}

func (s *GuidanceServiceServer) DeletePrecedenceRule(ctx context.Context, in *v1_guidancev1.DeletePrecedenceRuleRequest) (*v1_guidancev1.DeletePrecedenceRuleResponse, error) {
	l := logic.NewDeletePrecedenceRuleLogic(ctx, s.svcCtx)
	return l.DeletePrecedenceRule(in)
}

func (s *GuidanceServiceServer) ListPrecedenceRules(ctx context.Context, in *v1_guidancev1.ListPrecedenceRulesRequest) (*v1_guidancev1.ListPrecedenceRulesResponse, error) {
	l := logic.NewListPrecedenceRulesLogic(ctx, s.svcCtx)
	return l.ListPrecedenceRules(in)
}

func (s *GuidanceServiceServer) PreviewPreparationRules(ctx context.Context, in *v1_guidancev1.PreviewPreparationRulesRequest) (*v1_guidancev1.PreparationRulePreview, error) {
	l := logic.NewPreviewPreparationRulesLogic(ctx, s.svcCtx)
	return l.PreviewPreparationRules(in)
}

func (s *GuidanceServiceServer) GetExaminationItemConfiguration(ctx context.Context, in *v1_guidancev1.GetExaminationItemConfigurationRequest) (*v1_guidancev1.ExaminationItemConfiguration, error) {
	l := logic.NewGetExaminationItemConfigurationLogic(ctx, s.svcCtx)
	return l.GetExaminationItemConfiguration(in)
}

func (s *GuidanceServiceServer) ConfigureExaminationItem(ctx context.Context, in *v1_guidancev1.ConfigureExaminationItemRequest) (*v1_guidancev1.ExaminationItemConfiguration, error) {
	l := logic.NewConfigureExaminationItemLogic(ctx, s.svcCtx)
	return l.ConfigureExaminationItem(in)
}

func (s *GuidanceServiceServer) GenerateSmartAppointmentPlans(ctx context.Context, in *v1_guidancev1.GenerateSmartAppointmentPlansRequest) (*v1_guidancev1.SmartAppointmentPlansResponse, error) {
	l := logic.NewGenerateSmartAppointmentPlansLogic(ctx, s.svcCtx)
	return l.GenerateSmartAppointmentPlans(in)
}

func (s *GuidanceServiceServer) ConfirmSmartAppointmentPlan(ctx context.Context, in *v1_guidancev1.ConfirmSmartAppointmentPlanRequest) (*v1_guidancev1.ConfirmedSmartAppointmentPlan, error) {
	l := logic.NewConfirmSmartAppointmentPlanLogic(ctx, s.svcCtx)
	return l.ConfirmSmartAppointmentPlan(in)
}

func (s *GuidanceServiceServer) GetTodayExaminationRecommendation(ctx context.Context, in *v1_guidancev1.GetTodayExaminationRecommendationRequest) (*v1_guidancev1.TodayExaminationRecommendation, error) {
	l := logic.NewGetTodayExaminationRecommendationLogic(ctx, s.svcCtx)
	return l.GetTodayExaminationRecommendation(in)
}

func (s *GuidanceServiceServer) SearchPlaces(ctx context.Context, in *v1_guidancev1.SearchPlacesRequest) (*v1_guidancev1.SearchPlacesResponse, error) {
	l := logic.NewSearchPlacesLogic(ctx, s.svcCtx)
	return l.SearchPlaces(in)
}

func (s *GuidanceServiceServer) CalculateWalkingRoute(ctx context.Context, in *v1_guidancev1.CalculateWalkingRouteRequest) (*v1_guidancev1.WalkingRoute, error) {
	l := logic.NewCalculateWalkingRouteLogic(ctx, s.svcCtx)
	return l.CalculateWalkingRoute(in)
}
