// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: guidance.proto

package server

import (
	"context"

	v1_guidancev1 "hospital/contracts/gen/guidance/v1"
	"hospital/service/guidance/rpc/internal/logic"
	"hospital/service/guidance/rpc/internal/svc"
)

type GuidanceServiceServer struct {
	svcCtx *svc.ServiceContext
	v1_guidancev1.UnimplementedGuidanceServiceServer
}

func NewGuidanceServiceServer(svcCtx *svc.ServiceContext) *GuidanceServiceServer {
	return &GuidanceServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GuidanceServiceServer) CreatePrecedenceRule(ctx context.Context, in *v1_guidancev1.CreatePrecedenceRuleRequest) (*v1_guidancev1.PrecedenceRule, error) {
	l := logic.NewCreatePrecedenceRuleLogic(ctx, s.svcCtx)
	return l.CreatePrecedenceRule(in)
}

func (s *GuidanceServiceServer) UpdatePrecedenceRule(ctx context.Context, in *v1_guidancev1.UpdatePrecedenceRuleRequest) (*v1_guidancev1.PrecedenceRule, error) {
	l := logic.NewUpdatePrecedenceRuleLogic(ctx, s.svcCtx)
	return l.UpdatePrecedenceRule(in)
}

func (s *GuidanceServiceServer) DeletePrecedenceRule(ctx context.Context, in *v1_guidancev1.DeletePrecedenceRuleRequest) (*v1_guidancev1.DeletePrecedenceRuleResponse, error) {
	l := logic.NewDeletePrecedenceRuleLogic(ctx, s.svcCtx)
	return l.DeletePrecedenceRule(in)
}

func (s *GuidanceServiceServer) ListPrecedenceRules(ctx context.Context, in *v1_guidancev1.ListPrecedenceRulesRequest) (*v1_guidancev1.ListPrecedenceRulesResponse, error) {
	l := logic.NewListPrecedenceRulesLogic(ctx, s.svcCtx)
	return l.ListPrecedenceRules(in)
}
