// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: identity.proto

package server

import (
	"context"

	"hospital/contracts/gen/identity/v1"
	"hospital/service/identity/rpc/internal/logic"
	"hospital/service/identity/rpc/internal/svc"
)

type IdentityServiceServer struct {
	svcCtx *svc.ServiceContext
	identityv1.UnimplementedIdentityServiceServer
}

func NewIdentityServiceServer(svcCtx *svc.ServiceContext) *IdentityServiceServer {
	return &IdentityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServiceServer) SendPhoneLoginCode(ctx context.Context, in *identityv1.SendPhoneLoginCodeRequest) (*identityv1.SendPhoneLoginCodeResponse, error) {
	l := logic.NewSendPhoneLoginCodeLogic(ctx, s.svcCtx)
	return l.SendPhoneLoginCode(in)
}

func (s *IdentityServiceServer) PhoneLogin(ctx context.Context, in *identityv1.PhoneLoginRequest) (*identityv1.TokenPair, error) {
	l := logic.NewPhoneLoginLogic(ctx, s.svcCtx)
	return l.PhoneLogin(in)
}

func (s *IdentityServiceServer) WeChatLogin(ctx context.Context, in *identityv1.WeChatLoginRequest) (*identityv1.TokenPair, error) {
	l := logic.NewWeChatLoginLogic(ctx, s.svcCtx)
	return l.WeChatLogin(in)
}

func (s *IdentityServiceServer) SetMyPhone(ctx context.Context, in *identityv1.SetMyPhoneRequest) (*identityv1.PhoneBinding, error) {
	l := logic.NewSetMyPhoneLogic(ctx, s.svcCtx)
	return l.SetMyPhone(in)
}

func (s *IdentityServiceServer) FindAccountByPhone(ctx context.Context, in *identityv1.FindAccountByPhoneRequest) (*identityv1.AccountLookup, error) {
	l := logic.NewFindAccountByPhoneLogic(ctx, s.svcCtx)
	return l.FindAccountByPhone(in)
}

func (s *IdentityServiceServer) PromoteToDepartmentDoctor(ctx context.Context, in *identityv1.PromoteToDepartmentDoctorRequest) (*identityv1.AuthorizationContext, error) {
	l := logic.NewPromoteToDepartmentDoctorLogic(ctx, s.svcCtx)
	return l.PromoteToDepartmentDoctor(in)
}

func (s *IdentityServiceServer) GetAuthorizationContext(ctx context.Context, in *identityv1.GetAuthorizationContextRequest) (*identityv1.AuthorizationContext, error) {
	l := logic.NewGetAuthorizationContextLogic(ctx, s.svcCtx)
	return l.GetAuthorizationContext(in)
}

func (s *IdentityServiceServer) AssignRole(ctx context.Context, in *identityv1.AssignRoleRequest) (*identityv1.AuthorizationContext, error) {
	l := logic.NewAssignRoleLogic(ctx, s.svcCtx)
	return l.AssignRole(in)
}

func (s *IdentityServiceServer) ChangeStaffDepartment(ctx context.Context, in *identityv1.ChangeStaffDepartmentRequest) (*identityv1.AuthorizationContext, error) {
	l := logic.NewChangeStaffDepartmentLogic(ctx, s.svcCtx)
	return l.ChangeStaffDepartment(in)
}

func (s *IdentityServiceServer) ChangeAccountStatus(ctx context.Context, in *identityv1.ChangeAccountStatusRequest) (*identityv1.AuthorizationContext, error) {
	l := logic.NewChangeAccountStatusLogic(ctx, s.svcCtx)
	return l.ChangeAccountStatus(in)
}

func (s *IdentityServiceServer) RefreshAccessToken(ctx context.Context, in *identityv1.RefreshAccessTokenRequest) (*identityv1.TokenPair, error) {
	l := logic.NewRefreshAccessTokenLogic(ctx, s.svcCtx)
	return l.RefreshAccessToken(in)
}

func (s *IdentityServiceServer) RevokeRefreshToken(ctx context.Context, in *identityv1.RevokeRefreshTokenRequest) (*identityv1.RevokeRefreshTokenResponse, error) {
	l := logic.NewRevokeRefreshTokenLogic(ctx, s.svcCtx)
	return l.RevokeRefreshToken(in)
}

// Public organization directory. HTTP gateways may expose these methods
func (s *IdentityServiceServer) GetOrganizationContext(ctx context.Context, in *identityv1.GetOrganizationContextRequest) (*identityv1.OrganizationContext, error) {
	l := logic.NewGetOrganizationContextLogic(ctx, s.svcCtx)
	return l.GetOrganizationContext(in)
}

func (s *IdentityServiceServer) ListDepartments(ctx context.Context, in *identityv1.ListDepartmentsRequest) (*identityv1.ListDepartmentsResponse, error) {
	l := logic.NewListDepartmentsLogic(ctx, s.svcCtx)
	return l.ListDepartments(in)
}

// Administrator organization management.
func (s *IdentityServiceServer) ListOrganizationUnits(ctx context.Context, in *identityv1.ListOrganizationUnitsRequest) (*identityv1.ListOrganizationUnitsResponse, error) {
	l := logic.NewListOrganizationUnitsLogic(ctx, s.svcCtx)
	return l.ListOrganizationUnits(in)
}

func (s *IdentityServiceServer) GetOrganizationUnit(ctx context.Context, in *identityv1.GetOrganizationUnitRequest) (*identityv1.AdminOrganizationUnit, error) {
	l := logic.NewGetOrganizationUnitLogic(ctx, s.svcCtx)
	return l.GetOrganizationUnit(in)
}

func (s *IdentityServiceServer) CreateOrganizationUnit(ctx context.Context, in *identityv1.CreateOrganizationUnitRequest) (*identityv1.AdminOrganizationUnit, error) {
	l := logic.NewCreateOrganizationUnitLogic(ctx, s.svcCtx)
	return l.CreateOrganizationUnit(in)
}

func (s *IdentityServiceServer) UpdateOrganizationUnit(ctx context.Context, in *identityv1.UpdateOrganizationUnitRequest) (*identityv1.AdminOrganizationUnit, error) {
	l := logic.NewUpdateOrganizationUnitLogic(ctx, s.svcCtx)
	return l.UpdateOrganizationUnit(in)
}

func (s *IdentityServiceServer) DisableOrganizationUnit(ctx context.Context, in *identityv1.ChangeOrganizationUnitStatusRequest) (*identityv1.AdminOrganizationUnit, error) {
	l := logic.NewDisableOrganizationUnitLogic(ctx, s.svcCtx)
	return l.DisableOrganizationUnit(in)
}

func (s *IdentityServiceServer) EnableOrganizationUnit(ctx context.Context, in *identityv1.ChangeOrganizationUnitStatusRequest) (*identityv1.AdminOrganizationUnit, error) {
	l := logic.NewEnableOrganizationUnitLogic(ctx, s.svcCtx)
	return l.EnableOrganizationUnit(in)
}
