// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: identity.proto

package server

import (
	"context"

	"hospital/contracts/gen/identity/v1"
	"hospital/service/identity/rpc/internal/logic"
	"hospital/service/identity/rpc/internal/svc"
)

type IdentityServiceServer struct {
	svcCtx *svc.ServiceContext
	identityv1.UnimplementedIdentityServiceServer
}

func NewIdentityServiceServer(svcCtx *svc.ServiceContext) *IdentityServiceServer {
	return &IdentityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServiceServer) GetAuthorizationContext(ctx context.Context, in *identityv1.GetAuthorizationContextRequest) (*identityv1.AuthorizationContext, error) {
	l := logic.NewGetAuthorizationContextLogic(ctx, s.svcCtx)
	return l.GetAuthorizationContext(in)
}

func (s *IdentityServiceServer) AssignRole(ctx context.Context, in *identityv1.AssignRoleRequest) (*identityv1.AuthorizationContext, error) {
	l := logic.NewAssignRoleLogic(ctx, s.svcCtx)
	return l.AssignRole(in)
}

func (s *IdentityServiceServer) ChangeStaffDepartment(ctx context.Context, in *identityv1.ChangeStaffDepartmentRequest) (*identityv1.AuthorizationContext, error) {
	l := logic.NewChangeStaffDepartmentLogic(ctx, s.svcCtx)
	return l.ChangeStaffDepartment(in)
}

func (s *IdentityServiceServer) ChangeAccountStatus(ctx context.Context, in *identityv1.ChangeAccountStatusRequest) (*identityv1.AuthorizationContext, error) {
	l := logic.NewChangeAccountStatusLogic(ctx, s.svcCtx)
	return l.ChangeAccountStatus(in)
}

func (s *IdentityServiceServer) RefreshAccessToken(ctx context.Context, in *identityv1.RefreshAccessTokenRequest) (*identityv1.TokenPair, error) {
	l := logic.NewRefreshAccessTokenLogic(ctx, s.svcCtx)
	return l.RefreshAccessToken(in)
}

func (s *IdentityServiceServer) RevokeRefreshToken(ctx context.Context, in *identityv1.RevokeRefreshTokenRequest) (*identityv1.RevokeRefreshTokenResponse, error) {
	l := logic.NewRevokeRefreshTokenLogic(ctx, s.svcCtx)
	return l.RevokeRefreshToken(in)
}
