// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: identity.proto

package server

import (
	"context"

	"hospital/contracts/gen/identity/v1"
	"hospital/service/identity/rpc/internal/logic"
	"hospital/service/identity/rpc/internal/svc"
)

type IdentityServiceServer struct {
	svcCtx *svc.ServiceContext
	identityv1.UnimplementedIdentityServiceServer
}

func NewIdentityServiceServer(svcCtx *svc.ServiceContext) *IdentityServiceServer {
	return &IdentityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServiceServer) SendPhoneLoginCode(ctx context.Context, in *identityv1.SendPhoneLoginCodeRequest) (*identityv1.SendPhoneLoginCodeResponse, error) {
	l := logic.NewSendPhoneLoginCodeLogic(ctx, s.svcCtx)
	return l.SendPhoneLoginCode(in)
}

func (s *IdentityServiceServer) PhoneLogin(ctx context.Context, in *identityv1.PhoneLoginRequest) (*identityv1.TokenPair, error) {
	l := logic.NewPhoneLoginLogic(ctx, s.svcCtx)
	return l.PhoneLogin(in)
}

func (s *IdentityServiceServer) RefreshAccessToken(ctx context.Context, in *identityv1.RefreshAccessTokenRequest) (*identityv1.TokenPair, error) {
	l := logic.NewRefreshAccessTokenLogic(ctx, s.svcCtx)
	return l.RefreshAccessToken(in)
}

func (s *IdentityServiceServer) RevokeRefreshToken(ctx context.Context, in *identityv1.RevokeRefreshTokenRequest) (*identityv1.RevokeRefreshTokenResponse, error) {
	l := logic.NewRevokeRefreshTokenLogic(ctx, s.svcCtx)
	return l.RevokeRefreshToken(in)
}

func (s *IdentityServiceServer) GetAccountDisplayProfile(ctx context.Context, in *identityv1.GetAccountDisplayProfileRequest) (*identityv1.AccountDisplayProfile, error) {
	l := logic.NewGetAccountDisplayProfileLogic(ctx, s.svcCtx)
	return l.GetAccountDisplayProfile(in)
}

func (s *IdentityServiceServer) UpdateAccountDisplayProfile(ctx context.Context, in *identityv1.UpdateAccountDisplayProfileRequest) (*identityv1.AccountDisplayProfile, error) {
	l := logic.NewUpdateAccountDisplayProfileLogic(ctx, s.svcCtx)
	return l.UpdateAccountDisplayProfile(in)
}

// Public organization directory. HTTP gateways may expose these methods
func (s *IdentityServiceServer) GetOrganizationContext(ctx context.Context, in *identityv1.GetOrganizationContextRequest) (*identityv1.OrganizationContext, error) {
	l := logic.NewGetOrganizationContextLogic(ctx, s.svcCtx)
	return l.GetOrganizationContext(in)
}

func (s *IdentityServiceServer) ListDepartments(ctx context.Context, in *identityv1.ListDepartmentsRequest) (*identityv1.ListDepartmentsResponse, error) {
	l := logic.NewListDepartmentsLogic(ctx, s.svcCtx)
	return l.ListDepartments(in)
}

func (s *IdentityServiceServer) ListDoctorsByDepartment(ctx context.Context, in *identityv1.ListDoctorsByDepartmentRequest) (*identityv1.ListDoctorsByDepartmentResponse, error) {
	l := logic.NewListDoctorsByDepartmentLogic(ctx, s.svcCtx)
	return l.ListDoctorsByDepartment(in)
}

// Administrator organization management.
func (s *IdentityServiceServer) ListOrganizationUnits(ctx context.Context, in *identityv1.ListOrganizationUnitsRequest) (*identityv1.ListOrganizationUnitsResponse, error) {
	l := logic.NewListOrganizationUnitsLogic(ctx, s.svcCtx)
	return l.ListOrganizationUnits(in)
}

func (s *IdentityServiceServer) GetOrganizationUnit(ctx context.Context, in *identityv1.GetOrganizationUnitRequest) (*identityv1.AdminOrganizationUnit, error) {
	l := logic.NewGetOrganizationUnitLogic(ctx, s.svcCtx)
	return l.GetOrganizationUnit(in)
}

func (s *IdentityServiceServer) CreateOrganizationUnit(ctx context.Context, in *identityv1.CreateOrganizationUnitRequest) (*identityv1.AdminOrganizationUnit, error) {
	l := logic.NewCreateOrganizationUnitLogic(ctx, s.svcCtx)
	return l.CreateOrganizationUnit(in)
}

func (s *IdentityServiceServer) UpdateOrganizationUnit(ctx context.Context, in *identityv1.UpdateOrganizationUnitRequest) (*identityv1.AdminOrganizationUnit, error) {
	l := logic.NewUpdateOrganizationUnitLogic(ctx, s.svcCtx)
	return l.UpdateOrganizationUnit(in)
}

func (s *IdentityServiceServer) DisableOrganizationUnit(ctx context.Context, in *identityv1.ChangeOrganizationUnitStatusRequest) (*identityv1.AdminOrganizationUnit, error) {
	l := logic.NewDisableOrganizationUnitLogic(ctx, s.svcCtx)
	return l.DisableOrganizationUnit(in)
}

func (s *IdentityServiceServer) EnableOrganizationUnit(ctx context.Context, in *identityv1.ChangeOrganizationUnitStatusRequest) (*identityv1.AdminOrganizationUnit, error) {
	l := logic.NewEnableOrganizationUnitLogic(ctx, s.svcCtx)
	return l.EnableOrganizationUnit(in)
}

// Administrator account and doctor management.
func (s *IdentityServiceServer) ListAdminAccounts(ctx context.Context, in *identityv1.ListAdminAccountsRequest) (*identityv1.ListAdminAccountsResponse, error) {
	l := logic.NewListAdminAccountsLogic(ctx, s.svcCtx)
	return l.ListAdminAccounts(in)
}

func (s *IdentityServiceServer) GetAdminAccount(ctx context.Context, in *identityv1.GetAdminAccountRequest) (*identityv1.AdminAccountDetail, error) {
	l := logic.NewGetAdminAccountLogic(ctx, s.svcCtx)
	return l.GetAdminAccount(in)
}

func (s *IdentityServiceServer) SearchAdminAccountByPhone(ctx context.Context, in *identityv1.SearchAdminAccountByPhoneRequest) (*identityv1.SearchAdminAccountByPhoneResponse, error) {
	l := logic.NewSearchAdminAccountByPhoneLogic(ctx, s.svcCtx)
	return l.SearchAdminAccountByPhone(in)
}

func (s *IdentityServiceServer) PromoteDoctor(ctx context.Context, in *identityv1.PromoteDoctorRequest) (*identityv1.AdminAccountDetail, error) {
	l := logic.NewPromoteDoctorLogic(ctx, s.svcCtx)
	return l.PromoteDoctor(in)
}

func (s *IdentityServiceServer) UpdateDoctor(ctx context.Context, in *identityv1.UpdateDoctorRequest) (*identityv1.AdminAccountDetail, error) {
	l := logic.NewUpdateDoctorLogic(ctx, s.svcCtx)
	return l.UpdateDoctor(in)
}

func (s *IdentityServiceServer) ChangeDoctorDepartment(ctx context.Context, in *identityv1.ChangeDoctorDepartmentRequest) (*identityv1.AdminAccountDetail, error) {
	l := logic.NewChangeDoctorDepartmentLogic(ctx, s.svcCtx)
	return l.ChangeDoctorDepartment(in)
}

func (s *IdentityServiceServer) RevokeDoctor(ctx context.Context, in *identityv1.AccountMutationRequest) (*identityv1.AdminAccountDetail, error) {
	l := logic.NewRevokeDoctorLogic(ctx, s.svcCtx)
	return l.RevokeDoctor(in)
}

func (s *IdentityServiceServer) DisableAccount(ctx context.Context, in *identityv1.AccountMutationRequest) (*identityv1.AdminAccountDetail, error) {
	l := logic.NewDisableAccountLogic(ctx, s.svcCtx)
	return l.DisableAccount(in)
}

func (s *IdentityServiceServer) EnableAccount(ctx context.Context, in *identityv1.AccountMutationRequest) (*identityv1.AdminAccountDetail, error) {
	l := logic.NewEnableAccountLogic(ctx, s.svcCtx)
	return l.EnableAccount(in)
}
