// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: identity.proto

package identityservice

import (
	"context"

	identityv1 "hospital/contracts/gen/identity/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountLookup                    = identityv1.AccountLookup
	AssignRoleRequest                = identityv1.AssignRoleRequest
	AuthorizationContext             = identityv1.AuthorizationContext
	ChangeAccountStatusRequest       = identityv1.ChangeAccountStatusRequest
	ChangeStaffDepartmentRequest     = identityv1.ChangeStaffDepartmentRequest
	FindAccountByPhoneRequest        = identityv1.FindAccountByPhoneRequest
	GetAuthorizationContextRequest   = identityv1.GetAuthorizationContextRequest
	PhoneBinding                     = identityv1.PhoneBinding
	PhoneLoginRequest                = identityv1.PhoneLoginRequest
	PromoteToDepartmentDoctorRequest = identityv1.PromoteToDepartmentDoctorRequest
	RefreshAccessTokenRequest        = identityv1.RefreshAccessTokenRequest
	RevokeRefreshTokenRequest        = identityv1.RevokeRefreshTokenRequest
	RevokeRefreshTokenResponse       = identityv1.RevokeRefreshTokenResponse
	SetMyPhoneRequest                = identityv1.SetMyPhoneRequest
	SendPhoneLoginCodeRequest        = identityv1.SendPhoneLoginCodeRequest
	SendPhoneLoginCodeResponse       = identityv1.SendPhoneLoginCodeResponse
	TokenPair                        = identityv1.TokenPair
	WeChatLoginRequest               = identityv1.WeChatLoginRequest

	IdentityService interface {
		SendPhoneLoginCode(ctx context.Context, in *SendPhoneLoginCodeRequest, opts ...grpc.CallOption) (*SendPhoneLoginCodeResponse, error)
		PhoneLogin(ctx context.Context, in *PhoneLoginRequest, opts ...grpc.CallOption) (*TokenPair, error)
		WeChatLogin(ctx context.Context, in *WeChatLoginRequest, opts ...grpc.CallOption) (*TokenPair, error)
		SetMyPhone(ctx context.Context, in *SetMyPhoneRequest, opts ...grpc.CallOption) (*PhoneBinding, error)
		FindAccountByPhone(ctx context.Context, in *FindAccountByPhoneRequest, opts ...grpc.CallOption) (*AccountLookup, error)
		PromoteToDepartmentDoctor(ctx context.Context, in *PromoteToDepartmentDoctorRequest, opts ...grpc.CallOption) (*AuthorizationContext, error)
		GetAuthorizationContext(ctx context.Context, in *GetAuthorizationContextRequest, opts ...grpc.CallOption) (*AuthorizationContext, error)
		AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*AuthorizationContext, error)
		ChangeStaffDepartment(ctx context.Context, in *ChangeStaffDepartmentRequest, opts ...grpc.CallOption) (*AuthorizationContext, error)
		ChangeAccountStatus(ctx context.Context, in *ChangeAccountStatusRequest, opts ...grpc.CallOption) (*AuthorizationContext, error)
		RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...grpc.CallOption) (*TokenPair, error)
		RevokeRefreshToken(ctx context.Context, in *RevokeRefreshTokenRequest, opts ...grpc.CallOption) (*RevokeRefreshTokenResponse, error)
	}

	defaultIdentityService struct {
		cli zrpc.Client
	}
)

func (m *defaultIdentityService) SendPhoneLoginCode(ctx context.Context, in *SendPhoneLoginCodeRequest, opts ...grpc.CallOption) (*SendPhoneLoginCodeResponse, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.SendPhoneLoginCode(ctx, in, opts...)
}

func (m *defaultIdentityService) PhoneLogin(ctx context.Context, in *PhoneLoginRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.PhoneLogin(ctx, in, opts...)
}

func NewIdentityService(cli zrpc.Client) IdentityService {
	return &defaultIdentityService{
		cli: cli,
	}
}

func (m *defaultIdentityService) WeChatLogin(ctx context.Context, in *WeChatLoginRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.WeChatLogin(ctx, in, opts...)
}

func (m *defaultIdentityService) SetMyPhone(ctx context.Context, in *SetMyPhoneRequest, opts ...grpc.CallOption) (*PhoneBinding, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.SetMyPhone(ctx, in, opts...)
}

func (m *defaultIdentityService) FindAccountByPhone(ctx context.Context, in *FindAccountByPhoneRequest, opts ...grpc.CallOption) (*AccountLookup, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.FindAccountByPhone(ctx, in, opts...)
}

func (m *defaultIdentityService) PromoteToDepartmentDoctor(ctx context.Context, in *PromoteToDepartmentDoctorRequest, opts ...grpc.CallOption) (*AuthorizationContext, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.PromoteToDepartmentDoctor(ctx, in, opts...)
}

func (m *defaultIdentityService) GetAuthorizationContext(ctx context.Context, in *GetAuthorizationContextRequest, opts ...grpc.CallOption) (*AuthorizationContext, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.GetAuthorizationContext(ctx, in, opts...)
}

func (m *defaultIdentityService) AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*AuthorizationContext, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.AssignRole(ctx, in, opts...)
}

func (m *defaultIdentityService) ChangeStaffDepartment(ctx context.Context, in *ChangeStaffDepartmentRequest, opts ...grpc.CallOption) (*AuthorizationContext, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.ChangeStaffDepartment(ctx, in, opts...)
}

func (m *defaultIdentityService) ChangeAccountStatus(ctx context.Context, in *ChangeAccountStatusRequest, opts ...grpc.CallOption) (*AuthorizationContext, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.ChangeAccountStatus(ctx, in, opts...)
}

func (m *defaultIdentityService) RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.RefreshAccessToken(ctx, in, opts...)
}

func (m *defaultIdentityService) RevokeRefreshToken(ctx context.Context, in *RevokeRefreshTokenRequest, opts ...grpc.CallOption) (*RevokeRefreshTokenResponse, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.RevokeRefreshToken(ctx, in, opts...)
}
