// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: identity.proto

package identityservice

import (
	"context"

	"hospital/contracts/gen/identity/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountLookup                       = identityv1.AccountLookup
	AdminOrganizationUnit               = identityv1.AdminOrganizationUnit
	AssignRoleRequest                   = identityv1.AssignRoleRequest
	AuthorizationContext                = identityv1.AuthorizationContext
	CampusSummary                       = identityv1.CampusSummary
	ChangeAccountStatusRequest          = identityv1.ChangeAccountStatusRequest
	ChangeOrganizationUnitStatusRequest = identityv1.ChangeOrganizationUnitStatusRequest
	ChangeStaffDepartmentRequest        = identityv1.ChangeStaffDepartmentRequest
	CreateOrganizationUnitRequest       = identityv1.CreateOrganizationUnitRequest
	DepartmentSummary                   = identityv1.DepartmentSummary
	FindAccountByPhoneRequest           = identityv1.FindAccountByPhoneRequest
	GetAuthorizationContextRequest      = identityv1.GetAuthorizationContextRequest
	GetOrganizationContextRequest       = identityv1.GetOrganizationContextRequest
	GetOrganizationUnitRequest          = identityv1.GetOrganizationUnitRequest
	HospitalSummary                     = identityv1.HospitalSummary
	ListDepartmentsRequest              = identityv1.ListDepartmentsRequest
	ListDepartmentsResponse             = identityv1.ListDepartmentsResponse
	ListOrganizationUnitsRequest        = identityv1.ListOrganizationUnitsRequest
	ListOrganizationUnitsResponse       = identityv1.ListOrganizationUnitsResponse
	OrganizationContext                 = identityv1.OrganizationContext
	PhoneBinding                        = identityv1.PhoneBinding
	PhoneLoginRequest                   = identityv1.PhoneLoginRequest
	PromoteToDepartmentDoctorRequest    = identityv1.PromoteToDepartmentDoctorRequest
	RefreshAccessTokenRequest           = identityv1.RefreshAccessTokenRequest
	RevokeRefreshTokenRequest           = identityv1.RevokeRefreshTokenRequest
	RevokeRefreshTokenResponse          = identityv1.RevokeRefreshTokenResponse
	SendPhoneLoginCodeRequest           = identityv1.SendPhoneLoginCodeRequest
	SendPhoneLoginCodeResponse          = identityv1.SendPhoneLoginCodeResponse
	SetMyPhoneRequest                   = identityv1.SetMyPhoneRequest
	TokenPair                           = identityv1.TokenPair
	UpdateOrganizationUnitRequest       = identityv1.UpdateOrganizationUnitRequest
	WeChatLoginRequest                  = identityv1.WeChatLoginRequest

	IdentityService interface {
		SendPhoneLoginCode(ctx context.Context, in *SendPhoneLoginCodeRequest, opts ...grpc.CallOption) (*SendPhoneLoginCodeResponse, error)
		PhoneLogin(ctx context.Context, in *PhoneLoginRequest, opts ...grpc.CallOption) (*TokenPair, error)
		WeChatLogin(ctx context.Context, in *WeChatLoginRequest, opts ...grpc.CallOption) (*TokenPair, error)
		SetMyPhone(ctx context.Context, in *SetMyPhoneRequest, opts ...grpc.CallOption) (*PhoneBinding, error)
		FindAccountByPhone(ctx context.Context, in *FindAccountByPhoneRequest, opts ...grpc.CallOption) (*AccountLookup, error)
		PromoteToDepartmentDoctor(ctx context.Context, in *PromoteToDepartmentDoctorRequest, opts ...grpc.CallOption) (*AuthorizationContext, error)
		GetAuthorizationContext(ctx context.Context, in *GetAuthorizationContextRequest, opts ...grpc.CallOption) (*AuthorizationContext, error)
		AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*AuthorizationContext, error)
		ChangeStaffDepartment(ctx context.Context, in *ChangeStaffDepartmentRequest, opts ...grpc.CallOption) (*AuthorizationContext, error)
		ChangeAccountStatus(ctx context.Context, in *ChangeAccountStatusRequest, opts ...grpc.CallOption) (*AuthorizationContext, error)
		RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...grpc.CallOption) (*TokenPair, error)
		RevokeRefreshToken(ctx context.Context, in *RevokeRefreshTokenRequest, opts ...grpc.CallOption) (*RevokeRefreshTokenResponse, error)
		// Public organization directory. HTTP gateways may expose these methods
		GetOrganizationContext(ctx context.Context, in *GetOrganizationContextRequest, opts ...grpc.CallOption) (*OrganizationContext, error)
		ListDepartments(ctx context.Context, in *ListDepartmentsRequest, opts ...grpc.CallOption) (*ListDepartmentsResponse, error)
		// Administrator organization management.
		ListOrganizationUnits(ctx context.Context, in *ListOrganizationUnitsRequest, opts ...grpc.CallOption) (*ListOrganizationUnitsResponse, error)
		GetOrganizationUnit(ctx context.Context, in *GetOrganizationUnitRequest, opts ...grpc.CallOption) (*AdminOrganizationUnit, error)
		CreateOrganizationUnit(ctx context.Context, in *CreateOrganizationUnitRequest, opts ...grpc.CallOption) (*AdminOrganizationUnit, error)
		UpdateOrganizationUnit(ctx context.Context, in *UpdateOrganizationUnitRequest, opts ...grpc.CallOption) (*AdminOrganizationUnit, error)
		DisableOrganizationUnit(ctx context.Context, in *ChangeOrganizationUnitStatusRequest, opts ...grpc.CallOption) (*AdminOrganizationUnit, error)
		EnableOrganizationUnit(ctx context.Context, in *ChangeOrganizationUnitStatusRequest, opts ...grpc.CallOption) (*AdminOrganizationUnit, error)
	}

	defaultIdentityService struct {
		cli zrpc.Client
	}
)

func NewIdentityService(cli zrpc.Client) IdentityService {
	return &defaultIdentityService{
		cli: cli,
	}
}

func (m *defaultIdentityService) SendPhoneLoginCode(ctx context.Context, in *SendPhoneLoginCodeRequest, opts ...grpc.CallOption) (*SendPhoneLoginCodeResponse, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.SendPhoneLoginCode(ctx, in, opts...)
}

func (m *defaultIdentityService) PhoneLogin(ctx context.Context, in *PhoneLoginRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.PhoneLogin(ctx, in, opts...)
}

func (m *defaultIdentityService) WeChatLogin(ctx context.Context, in *WeChatLoginRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.WeChatLogin(ctx, in, opts...)
}

func (m *defaultIdentityService) SetMyPhone(ctx context.Context, in *SetMyPhoneRequest, opts ...grpc.CallOption) (*PhoneBinding, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.SetMyPhone(ctx, in, opts...)
}

func (m *defaultIdentityService) FindAccountByPhone(ctx context.Context, in *FindAccountByPhoneRequest, opts ...grpc.CallOption) (*AccountLookup, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.FindAccountByPhone(ctx, in, opts...)
}

func (m *defaultIdentityService) PromoteToDepartmentDoctor(ctx context.Context, in *PromoteToDepartmentDoctorRequest, opts ...grpc.CallOption) (*AuthorizationContext, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.PromoteToDepartmentDoctor(ctx, in, opts...)
}

func (m *defaultIdentityService) GetAuthorizationContext(ctx context.Context, in *GetAuthorizationContextRequest, opts ...grpc.CallOption) (*AuthorizationContext, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.GetAuthorizationContext(ctx, in, opts...)
}

func (m *defaultIdentityService) AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*AuthorizationContext, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.AssignRole(ctx, in, opts...)
}

func (m *defaultIdentityService) ChangeStaffDepartment(ctx context.Context, in *ChangeStaffDepartmentRequest, opts ...grpc.CallOption) (*AuthorizationContext, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.ChangeStaffDepartment(ctx, in, opts...)
}

func (m *defaultIdentityService) ChangeAccountStatus(ctx context.Context, in *ChangeAccountStatusRequest, opts ...grpc.CallOption) (*AuthorizationContext, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.ChangeAccountStatus(ctx, in, opts...)
}

func (m *defaultIdentityService) RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.RefreshAccessToken(ctx, in, opts...)
}

func (m *defaultIdentityService) RevokeRefreshToken(ctx context.Context, in *RevokeRefreshTokenRequest, opts ...grpc.CallOption) (*RevokeRefreshTokenResponse, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.RevokeRefreshToken(ctx, in, opts...)
}

// Public organization directory. HTTP gateways may expose these methods
func (m *defaultIdentityService) GetOrganizationContext(ctx context.Context, in *GetOrganizationContextRequest, opts ...grpc.CallOption) (*OrganizationContext, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.GetOrganizationContext(ctx, in, opts...)
}

func (m *defaultIdentityService) ListDepartments(ctx context.Context, in *ListDepartmentsRequest, opts ...grpc.CallOption) (*ListDepartmentsResponse, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.ListDepartments(ctx, in, opts...)
}

// Administrator organization management.
func (m *defaultIdentityService) ListOrganizationUnits(ctx context.Context, in *ListOrganizationUnitsRequest, opts ...grpc.CallOption) (*ListOrganizationUnitsResponse, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.ListOrganizationUnits(ctx, in, opts...)
}

func (m *defaultIdentityService) GetOrganizationUnit(ctx context.Context, in *GetOrganizationUnitRequest, opts ...grpc.CallOption) (*AdminOrganizationUnit, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.GetOrganizationUnit(ctx, in, opts...)
}

func (m *defaultIdentityService) CreateOrganizationUnit(ctx context.Context, in *CreateOrganizationUnitRequest, opts ...grpc.CallOption) (*AdminOrganizationUnit, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.CreateOrganizationUnit(ctx, in, opts...)
}

func (m *defaultIdentityService) UpdateOrganizationUnit(ctx context.Context, in *UpdateOrganizationUnitRequest, opts ...grpc.CallOption) (*AdminOrganizationUnit, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.UpdateOrganizationUnit(ctx, in, opts...)
}

func (m *defaultIdentityService) DisableOrganizationUnit(ctx context.Context, in *ChangeOrganizationUnitStatusRequest, opts ...grpc.CallOption) (*AdminOrganizationUnit, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.DisableOrganizationUnit(ctx, in, opts...)
}

func (m *defaultIdentityService) EnableOrganizationUnit(ctx context.Context, in *ChangeOrganizationUnitStatusRequest, opts ...grpc.CallOption) (*AdminOrganizationUnit, error) {
	client := identityv1.NewIdentityServiceClient(m.cli.Conn())
	return client.EnableOrganizationUnit(ctx, in, opts...)
}
